### PR TITLE
Bugfix/#152 pan to center

### LINKED ISSUE #152: ZoomImageView doesn't initially pan to center of the bitmap
- ZoomLayout 1.7.0/1
- Reproducible in official demo app: *Yes*
- Device / Android version: *Pixel, Android 10*

> For some reason when setting the image on the ZoomImageView, it doesn't pan to the center. It'll pan to the top, or bottom, but never the center regardless of what gravity or alignment I set.

> Currently the only way I can get it to center when initially setting the bitmap is to first call zoomImageView.setImageBitmap(bitmap) then set the pan to zoomImageView.panX / 2 and zoomImageView.panY / 2. This seems to work when the width and height of the content are bigger than the container(zoomImageView), however when either the width or height of the content is smaller than the container, the panx and pany both end up being 0, so this solution doesn't work. 

I recently opened a GitHub issue that ended up being closed as stale https://github.com/natario1/ZoomLayout/issues/135. Basically, I've gotten back to trying to repro the issue and now have a version of the sample app in which you'll be able to repro the issue.

https://github.com/King-Henry/ZoomLayout-Centering-Issue. This is the repository that contains the code to reproduce.

### PR DESCRIPTION
**Pull request by markusressel**
Honestly, I still can't quite wrap my head around how the matrix transformation stuff works, so I am not entirely sure if this is the right thing to do to fix the issue.

I tested the `ZoomImageView` on my device with different types of images of different size, and it works for all of them. I have **not** tested if code based functions like `panTo` or `moveTo` are affected by this. If I should do so please let me know.

It would probably be a good idea to add tests for these transformation functions since - at least for outside contributors - it is probably really hard to understand their intended and correct behavior, and a tiny change in code can have a massive impact on the functionality.

- Fixes #152
- Tests: *no*
- Docs updated: *no*

### Solution
As I discovered that your proposal code for centering an image in #47 did not work I found the code in `computeTransformationPan()` that did the exact same thing. Applying the `realZoom` to the content to match its `width` and `height` values with the `width` and `height` of the container fixed the issue.

Again, I don't understand every line of code in this lib yet, so, please have a thorough look and let me know if anything about this change worries you.

### CODE REVIEW

**Comment by markusressel** [comment]
Thinking about this, could this also be an issue in `computeTransformationZoom()`?

File: library/src/main/java/com/otaliastudios/zoom/ZoomEngine.kt [hunk 1]
```diff
@@ -607,8 +606,8 @@ internal constructor(context: Context) : ZoomApi {
      * dimensions. This means applying the transformation gravity.
      */
     private fun computeTransformationPan(): ScaledPoint {
-        val extraWidth = contentWidth - containerWidth
-        val extraHeight = contentHeight - containerHeight
+        val extraWidth = contentWidth * realZoom - containerWidth
+        val extraHeight = contentHeight * realZoom - containerHeight
```
Comment (markusressel) [inline library/src/main/java/com/otaliastudios/zoom/ZoomEngine.kt:610]: These are the important 2 lines.

**Review by natario1 — APPROVED** [review]
If it helps, anytime I go back to this repo after some time, I don't understand the code either. And that's because of bad naming I think (like, what the hell is a realZoom?). We should go through a big change and rethink/rename APIs at some point.

About this PR I'm a bit confused as to why it seemed to work just fine until now (the demo app correctly centers the image IIRC). But the changes you made seem to make sense to me, so if you know they fix the issue, let's merge this!

**Comment by markusressel** [comment]
My guess is that the issue is related to the dimensions of the device, the image, or the fact that multiple images are applied in succession (setImageDrawable) or a combination of those things.

**Comment by natario1** [comment]
I see. Feel free to merge when you're ready

**Comment by markusressel** [comment]
I have done some additional monkey testing and haven't found any issues, so I will merge and we will see if something explodes :sweat_smile:
